import os

SLACK_TOKEN = os.getenv("SLACK_URL")
SLACK_USERNAME = os.getenv("SLACK_USERNAME")
SLACK_CHANNEL = os.getenv("SLACK_CHANNEL", "#olark")
SLACK_PRESENCE_INTERVAL = int(os.getenv("SLACK_INTERVAL", 60))
SLACK_NOTIFICATION_INTERVAL = int(os.getenv("SLACK_NOTIFICATION_INTERVAL", 360))

OLARK_USERNAME = os.getenv("OLARK_USERNAME")
OLARK_PASSWORD = os.getenv("OLARK_PASSWORD")
OLARK_XMPP_HOST = os.getenv("OLARK_XMPP_HOST", "olark.com")
OLARK_XMPP_PORT = int(os.getenv("OLARK_XMPP_PASSWORD", 5222))
OLARK_WEBSERVICE_URL = os.getenv("OLARK_WEBSERVICE_URL", "https://chat.olark.com")
