import os


SLACK_TOKEN = os.getenv("OX_SLACK_TOKEN")
SLACK_USERNAME = os.getenv("OX_SLACK_USERNAME")
SLACK_CHANNEL = os.getenv("OX_SLACK_CHANNEL", "#olark")
SLACK_PRESENCE_INTERVAL = int(os.getenv("OX_SLACK_PRESENCE_INTERVAL", 60))
SLACK_NOTIFICATION_INTERVAL = int(os.getenv("OX_SLACK_NOTIFICATION_INTERVAL", 360))

OLARK_USERNAME = os.getenv("OX_OLARK_USERNAME")
OLARK_PASSWORD = os.getenv("OX_OLARK_PASSWORD")
OLARK_XMPP_HOST = os.getenv("OX_OLARK_XMPP_HOST", "olark.com")
OLARK_XMPP_PORT = int(os.getenv("OX_OLARK_XMPP_PASSWORD", 5222))
OLARK_WEBSERVICE_URL = os.getenv("OX_OLARK_WEBSERVICE_URL", "https://chat.olark.com")
